# Site settings
title: Gareth's Different Circle Tech Blog
email: gareth@ibas.org.uk
description: > # this means to ignore newlines until "baseurl:"
  Here, on this cool thing, I'll be maintaining the history of building the Different Circle platform
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ThatsMrGeeToYou
github_username:  gmcnicol

# Build settings
markdown: kramdown
